# Task 4.8
### contents

### 1. import libraries
### 2. import data 
### 3. if statement: user defined
### 4. if statement: loc()
### 5. if statement: for loop
### 6. task 4.7 #2
### 7. task 4.7 #4

## 1. import libraries

In [17]:
import pandas as pd
import numpy as np
import os
import time

## 2. import task 4.6 final merged data file

In [2]:
%%time
path = r"C:\Users\andre\OneDrive\Documents\coursework 2022\CF\Immersion\Achievement 4\Instacart Basket Analysis\02 Data\Prepared Data\4.7.pkl"
ords_prods_merge = pd.read_pickle(path)

CPU times: total: 11.4 s
Wall time: 15.6 s

### check

In [3]:
%%time
ords_prods_merge

CPU times: total: 0 ns
Wall time: 0 ns

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Mid-range,Regularly busy,Regularly busy,Average orders
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range,Regularly busy,Least busy days,Average orders
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range,Regularly busy,Least busy days,Most orders
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range,Least busy,Least busy days,Average orders
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range,Least busy,Least busy days,Most orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,1320836,202557,prior,17,2,15,1.0,43553,2,1,Orange Energy Shots,64,7,3.7,Low-range product,Low-range,Regularly busy,Regularly busy,Most orders
32404855,31526,202557,prior,18,5,11,3.0,43553,2,1,Orange Energy Shots,64,7,3.7,Low-range product,Low-range,Regularly busy,Regularly busy,Average orders
32404856,758936,203436,prior,1,2,7,NaN,42338,4,0,"Zucchini Chips, Pesto",50,19,6.9,Mid-range product,Mid-range,Regularly busy,Regularly busy,Average orders
32404857,2745165,203436,prior,2,3,5,15.0,42338,16,1,"Zucchini Chips, Pesto",50,19,6.9,Mid-range product,Mid-range,Regularly busy,Least busy days,Fewest orders
32404858,3093936,205420,prior,1,4,14,NaN,28818,8,0,Hot Oatmeal Multigrain Raisin,130,14,10.3,Mid-range product,Mid-range,Least busy,Least busy days,Most orders

#drop the duplicated column price_range (user defined function- if statement- from 4.7)

In [6]:
%%time
ords_prods_merge = pd.read_pickle(path).drop(['price_range'], axis = 1)

CPU times: total: 16.6 s
Wall time: 16.8 s

In [7]:
%%time
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 18 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                object
 1   user_id                 object
 2   eval_set                object
 3   order_number            int64
 4   orders_day_of_week      int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
 7   product_id              int64
 8   add_to_cart_order       int64
 9   reordered               int64
 10  product_name            object
 11  aisle_id                int64
 12  department_id           int64
 13  prices                  float64
 14  price_range_loc         object
 15  busiest_day             object
 16  busiest_days            object
 17  busiest_period_of_day   object
dtypes: float64(2), int64(8), object(8)
memory usage: 4.6+ GB
CPU times: total: 0 ns
Wall time: 15.1 ms

In [8]:
%%time
ords_prods_merge.describe()

CPU times: total: 5.52 s
Wall time: 5.69 s

,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,aisle_id,department_id,prices
count,3.240486e+07,3.240486e+07,3.240486e+07,3.032876e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07
mean,1.714230e+01,2.738867e+00,1.342515e+01,1.110408e+01,2.559866e+04,8.352547e+00,5.895873e-01,7.119612e+01,9.919792e+00,1.198023e+01
std,1.753532e+01,2.090077e+00,4.246380e+00,8.779064e+00,1.408400e+04,7.127071e+00,4.919087e-01,3.821139e+01,6.281485e+00,4.956554e+02
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,1.354400e+04,3.000000e+00,0.000000e+00,3.100000e+01,4.000000e+00,4.200000e+00
50%,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,2.530200e+04,6.000000e+00,1.000000e+00,8.300000e+01,9.000000e+00,7.400000e+00
75%,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,3.794700e+04,1.100000e+01,1.000000e+00,1.070000e+02,1.600000e+01,1.130000e+01
max,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01,4.968800e+04,1.450000e+02,1.000000e+00,1.340000e+02,2.100000e+01,9.999900e+04

## 3. excercise 4.8 practice

In [9]:
# create subset 
df = ords_prods_merge[:1000000]

In [10]:
#check
df.shape

(1000000, 18)

### groupby() has 3 parts:
### 1 Split the data into groups based on some criteria.
### 2 Apply a function to each group separately.
### 3 Combine the results into a dataframe or alternative data structure or create a new column in the current dataframe.

In [11]:
#group by function part 1
df.groupby('product_name')

In [12]:
#part 1 & 2 using the agg() function
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [13]:
#part 1 & 2 using mean() command with square brackets
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [14]:
#part 1&2 using mean command in dot notation, poor coding compared to sq. bracket 
df.groupby('department_id').order_number.mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

### multiple aggregations

In [15]:
%%time
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

CPU times: total: 15.6 ms
Wall time: 30.4 ms

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

### transform() function for aggregating with criteria:
* If the maximum orders the user has made is over 40, then the customer will be labeled a “Loyal customer.”
* If the maximum orders the user has made is over 10 but less than or equal to 40, then the customer will be labeled a “Regular customer.”
* If the maximum orders the user has made is less than or equal to 10, then the customer will be labeled a “New customer.”

In [18]:
%%time
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

CPU times: total: 2.88 s
Wall time: 2.93 s

In [21]:
#change default settings to allow for display of 100 rows 
pd.options.display.max_rows = 100

#check

In [22]:
%%time
ords_prods_merge.head(100)

CPU times: total: 0 ns
Wall time: 0 ns

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Most orders,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,10
6,550135,1,prior,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,22
14,487368,15,prior,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,22
15,2293453,19,prior,2,5,14,6.0,196,3,0,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,9
16,1973799,19,prior,5,6,12,8.0,196,15,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,9
17,532817,19,prior,7,4,17,6.0,196,1,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,9
18,1573906,21,prior,10,3,10,6.0,196,2,0,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,33
19,1593000,31,prior,10,3,8,7.0,196,17,0,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,20
20,2231262,31,prior,17,3,11,8.0,196,14,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,20
21,2580647,43,prior,6,4,16,4.0,196,9,0,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,11
22,2187180,43,prior,9,4,12,3.0,196,1,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Most orders,11
23,2497897,52,prior,1,1,9,NaN,196,4,0,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,27
24,1318871,52,prior,2,1,10,7.0,196,5,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,27
25,1261384,52,prior,3,1,10,7.0,196,3,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,27
26,580568,52,prior,5,2,10,8.0,196,6,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
27,2428073,52,prior,7,2,7,8.0,196,5,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
28,342306,52,prior,9,1,11,7.0,196,5,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,27
29,1520353,52,prior,10,2,10,8.0,196,4,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
30,2542086,52,prior,11,2,9,7.0,196,3,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
31,944694,52,prior,12,1,16,6.0,196,7,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,27
32,1268191,52,prior,15,2,11,8.0,196,3,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
33,1122089,52,prior,17,2,10,6.0,196,4,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
34,1498922,52,prior,18,2,10,14.0,196,6,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
35,180919,52,prior,19,3,8,8.0,196,4,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,27
36,2695875,52,prior,21,5,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,27
37,3205960,67,prior,1,3,11,NaN,196,1,0,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,24
38,970922,67,prior,2,1,15,5.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,24
39,596585,67,prior,3,1,13,7.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,24
40,2037087,67,prior,4,2,9,8.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,24
41,2474111,67,prior,5,3,14,8.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Most orders,24
42,1568481,67,prior,6,3,12,7.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Most orders,24
43,2048527,67,prior,8,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,24
44,2389031,67,prior,9,2,14,7.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,24
45,2378562,67,prior,10,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,24
46,1515698,67,prior,11,1,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,24
47,1928050,67,prior,12,2,12,8.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,24
48,1949274,67,prior,13,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,24
49,551869,67,prior,14,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,24
50,768572,67,prior,16,4,10,9.0,196,1,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,24
51,150528,67,prior,18,5,16,4.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,24
52,29758,67,prior,19,0,14,9.0,196,2,1,Soda,77,7,9.0,Mid-range,Busiest day,Busiest days,Most orders,24
53,1558976,67,prior,21,1,9,5.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,24
54,863974,67,prior,22,1,11,14.0,196,3,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,24
55,2308399,67,prior,23,1,14,14.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,24
56,2759128,81,prior,3,1,9,14.0,196,2,0,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,7
57,1812985,81,prior,5,2,20,30.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,7
58,1889835,82,prior,1,3,15,NaN,196,6,0,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Most orders,19
59,499460,82,prior,3,5,10,5.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,19
60,2728456,82,prior,4,0,11,16.0,196,1,1,Soda,77,7,9.0,Mid-range,Busiest day,Busiest days,Average orders,19
61,2653743,82,prior,6,4,9,13.0,196,5,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,19
62,1358880,82,prior,9,1,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,19
63,343588,82,prior,10,2,11,1.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,19
64,3034663,82,prior,15,2,11,12.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,19
65,147262,82,prior,18,1,13,7.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,19
66,3144004,82,prior,19,2,15,8.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,19
67,2126069,98,prior,3,0,9,25.0,196,7,0,Soda,77,7,9.0,Mid-range,Busiest day,Busiest days,Average orders,14
68,2210120,98,prior,7,5,14,5.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,14
69,681011,98,prior,9,3,9,30.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,14
70,2846344,98,prior,11,4,13,15.0,196,2,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Most orders,14
71,747431,98,prior,12,6,13,30.0,196,4,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,14
72,2383054,98,prior,13,4,11,30.0,196,1,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,14
73,1993729,98,prior,14,5,8,8.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,14
74,1403849,109,prior,3,3,17,9.0,196,5,0,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,6
75,520620,120,prior,1,3,11,NaN,196,2,0,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,3
76,3273029,120,prior,3,2,8,19.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,3
77,1861943,185,prior,2,1,12,25.0,196,10,0,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,6
78,2040988,195,prior,1,1,14,NaN,196,2,0,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,58
79,1680569,195,prior,8,1,9,4.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,58
80,276171,195,prior,19,5,11,3.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,58
81,2744976,195,prior,22,5,10,7.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,58
82,2781919,195,prior,25,1,14,4.0,196,1,1,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Most orders,58
83,1738718,195,prior,31,2,8,4.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,58
84,3058369,195,prior,34,3,10,6.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,58
85,1485596,195,prior,37,2,15,0.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,58
86,417035,195,prior,40,3,16,2.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,58
87,1615297,195,prior,47,5,10,2.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,58
88,1765587,195,prior,52,3,12,2.0,196,3,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Most orders,58
89,745908,195,prior,57,4,11,3.0,196,3,1,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,58
90,2505656,222,prior,17,2,12,1.0,196,2,0,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,70
91,3268370,222,prior,38,5,15,1.0,196,6,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,70
92,2016711,290,prior,9,5,19,6.0,196,8,0,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,51
93,2706088,290,prior,28,6,10,7.0,196,16,1,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,51
94,1952286,331,prior,6,5,16,30.0,196,8,0,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,8
95,3226575,360,prior,1,5,12,NaN,196,1,0,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Most orders,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,Soda,77,7,9.0,Mid-range,Regularly busy,Regularly busy,Average orders,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,Soda,77,7,9.0,Mid-range,Least busy,Least busy days,Average orders,8
98,858092,420,prior,4,1,19,30.0,196,2,0,Soda,77,7,9.0,Mid-range,Regularly busy,Busiest days,Average orders,22
99,119314,420,prior,5,3,19,16.0,196,2,1,Soda,77,7,9.0,Mid-range,Regularly busy,Least busy days,Average orders,22

### create flag column using loc()

In [23]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [24]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [25]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [26]:
#check
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [27]:
#check 60 rows of select columns (optimized code) sq brackets required to indicate a list, also the variables to call
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

   user_id      loyalty_flag  order_number
0        1      New customer             1
1        1      New customer             2
2        1      New customer             3
3        1      New customer             4
4        1      New customer             5
5        1      New customer             6
6        1      New customer             7
7        1      New customer             8
8        1      New customer             9
9        1      New customer            10
10      15  Regular customer            15
11      15  Regular customer            17
12      15  Regular customer            18
13      15  Regular customer            21
14      15  Regular customer            22
15      19      New customer             2
16      19      New customer             5
17      19      New customer             7
18      21  Regular customer            10
19      31  Regular customer            10
20      31  Regular customer            17
21      43  Regular customer             6
22      43  Regular customer             9
23      52  Regular customer             1
24      52  Regular customer             2
25      52  Regular customer             3
26      52  Regular customer             5
27      52  Regular customer             7
28      52  Regular customer             9
29      52  Regular customer            10
30      52  Regular customer            11
31      52  Regular customer            12
32      52  Regular customer            15
33      52  Regular customer            17
34      52  Regular customer            18
35      52  Regular customer            19
36      52  Regular customer            21
37      67  Regular customer             1
38      67  Regular customer             2
39      67  Regular customer             3
40      67  Regular customer             4
41      67  Regular customer             5
42      67  Regular customer             6
43      67  Regular customer             8
44      67  Regular customer             9
45      67  Regular customer            10
46      67  Regular customer            11
47      67  Regular customer            12
48      67  Regular customer            13
49      67  Regular customer            14
50      67  Regular customer            16
51      67  Regular customer            18
52      67  Regular customer            19
53      67  Regular customer            21
54      67  Regular customer            22
55      67  Regular customer            23
56      81      New customer             3
57      81      New customer             5
58      82  Regular customer             1
59      82  Regular customer             3

### cleaning outliers

In [1]:
ords_prods_merge['prices'].describe()

NameError: name 'ords_prods_merge' is not defined

In [ ]:
#view on scatterplot
sns.scatterplot(x = 'prices', y = 'prices',data = ords_prods_merge)

In [ ]:
#view outlier data with prices above $100 (the value is used ad hoc) 
ords_prods_merge.loc[ords_prods_merge['prices'] > 100]

In [ ]:
#replace outliers with null 
ords_prods_merge.loc[ords_prods_merge['prices'] >100, 'prices'] = np.nan

In [ ]:
#save file as pkl
#ords_prods_merged.to_pickle(r'C:\Users\andre\OneDrive\Documents\coursework 2022\CF\Immersion\Achievement 4\Instacart Basket Analysis\02 Data\Prepared Data\4.7.pkl')